<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\XInfo.Gateway.Contracts\XInfo.Gateway.Contracts.csproj" />
    <ProjectReference Include="..\XInfo.Gateway.Data\XInfo.Gateway.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
